Add a unit test for the identity script
mendersoftware/mender-python-client pull request #12
Opened 2021-01-18 17:44 UTC by oleorhagen

Also added a type hint to the aggregator function

2021-01-19 05:28 UTC, lluiscampos requested changes
Sorry but I think the test is not good enough. See comment below.

2021-01-19 05:28 UTC, lluiscampos commented on tests/unit/test_script_aggregator.py
> +        assert identity_data
assert what? maybe `assert len(identity_data) > 0`?

Also, the script seems to be a copy of the production one. So if we were to verify the script itself, we should here assert on things that we expect, like mac key or something. Alternatively, if we want to test the Python module `identity` (which seems to be the case) then is best to replace the script dummy echos on known values and assert on than.

2021-01-19 05:28 UTC, lluiscampos commented on tests/unit/test_script_aggregator.py
> +        assert not identity_data
Maybe:
```suggestion
        assert identity_data == {}
```

2021-01-19 08:46 UTC, oleorhagen commented
Yes, you're right. This was a little too quick and dirty. I will redo it proper.

2021-01-19 13:59 UTC, olehermanse commented on tests/unit/test_script_aggregator.py
> +        assert identity_data
FYI, in general, @oleorhagen 's approach is considered much more pythonic / best practice in Python.

`assert something` is good. You want to assert that there is some identity data, not nothing (`None`, `()`, `[]`, `{}`). And vice versa, for `assert not something`.

Do you really care if `identity_data` has a `len()`? It might not be necessary, it could be a generator? Should you also assert something about the type of `identity_data`? If you want to go down that route, it might make sense to start using [type hints](https://docs.python.org/3/library/typing.html):

```python
def aggregate(path: str) -> list:
    [...]
```

It could also be that `assert len(identity_data) > 0` is exactly what you want, you need it to have a len and you expect to use it like that, so you do want to assert that it is possible to do `len` and that returns more than zero, because this is how you will use it.

Of course, I don't know anything about this code or project, so take everything I say with a large grain of salt.

2021-01-21 09:18 UTC, lluiscampos approved these changes
Thanks for the rework with the new test scripts

2021-01-21 09:18 UTC, lluiscampos commented on tests/unit/test_script_aggregator.py
> +    """,
Not that matters much, but I would align this same way as the other script.
```suggestion
                """#! /bin/sh
                echo mac=c8:5b:76:fb:c8:75""",
```

2021-01-21 09:23 UTC, merged